server:
  port: 8090

# ????
wxmini:
  appid: "wx3c86c641313e6426"
  secret: "c63729874cefc16da42c8fb5ada52c14"

ip : 121.4.79.106

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/couseling
    username: pslg
    password: abc123456
  redis:
    host: ${ip}
    port: 6379
    database: 0
    password: abc123456

mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  typeAliasesPackage: com.example.psychologybackend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

    #id类型。



